# Generated by Django 4.1.3 on 2022-12-17 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='pub_date',
        ),
    ]
