# Generated by Django 4.1.3 on 2022-12-24 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='zipcode',
        ),
    ]
