# Generated by Django 4.1.3 on 2022-12-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_orders_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='zipcode',
            field=models.CharField(default='', max_length=90),
        ),
    ]
